/*
 *  Copyright (c) 2026, WSO2 LLC. (http://www.wso2.org) All Rights Reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

// Package aicontentdisclosure marks AI-generated replies as such (EU AI Act
// Article 50 and similar transparency mandates). Never blocks traffic - see
// policy-definition.yaml for the full behavior.
package aicontentdisclosure

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"unicode/utf8"

	policy "github.com/wso2/api-platform/sdk/core/policy/v1alpha2"
)

const (
	placementAppend   = "append"
	placementPrepend  = "prepend"
	placementMetadata = "metadata-only"

	markerStart = '⁠' // WORD JOINER - start/end delimiter for the invisible tag
	markerZero  = '​' // ZERO WIDTH SPACE - bit 0
	markerOne   = '‌' // ZERO WIDTH NON-JOINER - bit 1
)

type config struct {
	disclosureText         string
	placement              string
	disclosureStandard     string
	addHeader              bool
	embedInvisibleMarker   bool
	invisibleMarkerTag     string
	contentPath            string
	skipIfAlreadyDisclosed bool
	minContentChars        int
}

// AiContentDisclosurePolicy implements the v1alpha2 policy interface.
type AiContentDisclosurePolicy struct{ cfg config }

// GetPolicy is the v1alpha2 factory entry point.
func GetPolicy(_ policy.PolicyMetadata, params map[string]interface{}) (policy.Policy, error) {
	cfg := config{
		disclosureText:         "This content was generated by an AI system.",
		placement:              placementAppend,
		disclosureStandard:     "eu-ai-act-art50",
		addHeader:              true,
		invisibleMarkerTag:     "AI-GEN",
		contentPath:            "$.choices[0].message.content",
		skipIfAlreadyDisclosed: true,
		minContentChars:        1,
	}

	strOpt(params, "disclosureText", &cfg.disclosureText)
	if v, ok := params["placement"]; ok {
		s, _ := v.(string)
		if s != placementAppend && s != placementPrepend && s != placementMetadata {
			return nil, wrap(fmt.Errorf("'placement' must be one of append, prepend, metadata-only"))
		}
		cfg.placement = s
	}
	strOpt(params, "disclosureStandard", &cfg.disclosureStandard)
	if err := boolParam(params, "addHeader", &cfg.addHeader); err != nil {
		return nil, wrap(err)
	}
	if err := boolParam(params, "embedInvisibleMarker", &cfg.embedInvisibleMarker); err != nil {
		return nil, wrap(err)
	}
	if v, ok := params["invisibleMarkerTag"]; ok {
		s, ok := v.(string)
		if !ok || s == "" || !isASCIIPrintable(s) || len(s) > 32 {
			return nil, wrap(fmt.Errorf("'invisibleMarkerTag' must be a non-empty printable ASCII string of at most 32 characters"))
		}
		cfg.invisibleMarkerTag = s
	}
	strOpt(params, "contentJsonPath", &cfg.contentPath)
	if err := boolParam(params, "skipIfAlreadyDisclosed", &cfg.skipIfAlreadyDisclosed); err != nil {
		return nil, wrap(err)
	}
	if v, ok := params["minContentChars"]; ok {
		f, err := toFloat(v)
		if err != nil || f < 0 {
			return nil, wrap(fmt.Errorf("'minContentChars' must be a number >= 0"))
		}
		cfg.minContentChars = int(f)
	}

	return &AiContentDisclosurePolicy{cfg: cfg}, nil
}

// Mode buffers the response body only.
func (p *AiContentDisclosurePolicy) Mode() policy.ProcessingMode {
	return policy.ProcessingMode{
		RequestHeaderMode:  policy.HeaderModeSkip,
		RequestBodyMode:    policy.BodyModeSkip,
		ResponseHeaderMode: policy.HeaderModeSkip,
		ResponseBodyMode:   policy.BodyModeBuffer,
	}
}

// OnResponseBody labels the reply and, unless placement is metadata-only,
// rewrites its text to carry the disclosure. Always forwards the response.
func (p *AiContentDisclosurePolicy) OnResponseBody(_ context.Context, respCtx *policy.ResponseContext, _ map[string]interface{}) policy.ResponseAction {
	var body []byte
	if respCtx.ResponseBody != nil {
		body = respCtx.ResponseBody.Content
	}
	content, ok, err := extractString(body, p.cfg.contentPath)
	if err != nil || !ok || utf8.RuneCountInString(content) < p.cfg.minContentChars {
		return policy.DownstreamResponseModifications{}
	}

	alreadyDisclosed := p.cfg.skipIfAlreadyDisclosed && p.isDisclosed(content)

	newContent := content
	changed := false
	if !alreadyDisclosed {
		if p.cfg.placement != placementMetadata {
			switch p.cfg.placement {
			case placementPrepend:
				newContent = p.cfg.disclosureText + "\n\n" + newContent
			default:
				newContent = newContent + "\n\n" + p.cfg.disclosureText
			}
			changed = true
		}
		if p.cfg.embedInvisibleMarker {
			marker := encodeInvisibleTag(p.cfg.invisibleMarkerTag)
			if p.cfg.placement == placementPrepend {
				newContent = marker + newContent
			} else {
				newContent = newContent + marker
			}
			changed = true
		}
	}

	headers := map[string]string{}
	if p.cfg.addHeader {
		headers["x-ai-generated"] = "true"
		headers["x-ai-disclosure-standard"] = p.cfg.disclosureStandard
	}

	analytics := map[string]any{
		"guardrailName":      "AiContentDisclosure",
		"aiGenerated":        true,
		"disclosureStandard": p.cfg.disclosureStandard,
		"disclosureApplied":  changed,
		"alreadyDisclosed":   alreadyDisclosed,
	}

	if !changed {
		return policy.DownstreamResponseModifications{HeadersToSet: headers, AnalyticsMetadata: analytics}
	}

	newBody, werr := setString(body, p.cfg.contentPath, newContent)
	if werr != nil {
		// Couldn't rewrite the body - still disclose via header/metadata
		// rather than silently dropping the transparency signal.
		return policy.DownstreamResponseModifications{HeadersToSet: headers, AnalyticsMetadata: analytics}
	}
	if len(headers) > 0 {
		headers["Content-Type"] = "application/json"
	}
	return policy.DownstreamResponseModifications{Body: newBody, HeadersToSet: headers, AnalyticsMetadata: analytics}
}

func (p *AiContentDisclosurePolicy) isDisclosed(content string) bool {
	if p.cfg.placement != placementMetadata && p.cfg.disclosureText != "" && strings.Contains(content, p.cfg.disclosureText) {
		return true
	}
	if p.cfg.embedInvisibleMarker {
		if tag, ok := decodeInvisibleTag(content); ok && tag == p.cfg.invisibleMarkerTag {
			return true
		}
	}
	return false
}

// ─── invisible marker (zero-width encoding) ──────────────────────────────────

// encodeInvisibleTag encodes tag as a run of zero-width characters bracketed
// by WORD JOINER delimiters: each byte becomes 8 zero-width runes (MSB
// first), ZERO WIDTH SPACE for a 0 bit and ZERO WIDTH NON-JOINER for a 1 bit.
// Invisible to a human reader, round-trips exactly via decodeInvisibleTag.
func encodeInvisibleTag(tag string) string {
	var b strings.Builder
	b.WriteRune(markerStart)
	for _, c := range []byte(tag) {
		for i := 7; i >= 0; i-- {
			if c&(1<<uint(i)) != 0 {
				b.WriteRune(markerOne)
			} else {
				b.WriteRune(markerZero)
			}
		}
	}
	b.WriteRune(markerStart)
	return b.String()
}

// decodeInvisibleTag finds the first markerStart...markerStart span and
// decodes it back into the original tag string. Returns ok=false if no
// well-formed span is present.
func decodeInvisibleTag(s string) (string, bool) {
	runes := []rune(s)
	start := -1
	for i, r := range runes {
		if r == markerStart {
			start = i
			break
		}
	}
	if start < 0 {
		return "", false
	}
	end := -1
	for i := start + 1; i < len(runes); i++ {
		if runes[i] == markerStart {
			end = i
			break
		}
	}
	if end < 0 {
		return "", false
	}
	bits := runes[start+1 : end]
	if len(bits)%8 != 0 || len(bits) == 0 {
		return "", false
	}
	out := make([]byte, 0, len(bits)/8)
	for i := 0; i < len(bits); i += 8 {
		var b byte
		for j := 0; j < 8; j++ {
			b <<= 1
			switch bits[i+j] {
			case markerOne:
				b |= 1
			case markerZero:
				// bit stays 0
			default:
				return "", false // not a well-formed marker span
			}
		}
		out = append(out, b)
	}
	return string(out), true
}

// ─── JSON get/set (shared minimal JSONPath, same pattern as other
// response-phase guardrails in this repo) ─────────────────────────────────

func extractString(body []byte, path string) (string, bool, error) {
	if len(body) == 0 {
		return "", false, nil
	}
	var root interface{}
	if err := json.Unmarshal(body, &root); err != nil {
		return "", false, fmt.Errorf("body is not JSON")
	}
	v := valueAt(root, path)
	s, ok := v.(string)
	return s, ok, nil
}

func setString(body []byte, path, value string) ([]byte, error) {
	var root interface{}
	if err := json.Unmarshal(body, &root); err != nil {
		return nil, err
	}
	if err := assign(root, path, value); err != nil {
		return nil, err
	}
	return json.Marshal(root)
}

func valueAt(root interface{}, jsonPath string) interface{} {
	cur := root
	p := strings.TrimPrefix(strings.TrimPrefix(jsonPath, "$"), ".")
	if p == "" {
		return cur
	}
	for _, comp := range strings.Split(p, ".") {
		if comp == "" {
			continue
		}
		key, idx, hasIdx := comp, 0, false
		if o := strings.IndexByte(comp, '['); o >= 0 && strings.HasSuffix(comp, "]") {
			key = comp[:o]
			hasIdx = true
			in := comp[o+1 : len(comp)-1]
			n, neg := 0, false
			for _, c := range in {
				if c == '-' {
					neg = true
					continue
				}
				if c < '0' || c > '9' {
					n = 0
					break
				}
				n = n*10 + int(c-'0')
			}
			if neg {
				n = -n
			}
			idx = n
		}
		if key != "" {
			m, ok := cur.(map[string]interface{})
			if !ok {
				return nil
			}
			cur = m[key]
		}
		if hasIdx {
			a, ok := cur.([]interface{})
			if !ok || len(a) == 0 {
				return nil
			}
			switch {
			case idx < 0:
				if -idx > len(a) {
					return nil
				}
				cur = a[len(a)+idx]
			case idx < len(a):
				cur = a[idx]
			default:
				return nil
			}
		}
	}
	return cur
}

func assign(root interface{}, jsonPath, value string) error {
	p := strings.TrimPrefix(strings.TrimPrefix(jsonPath, "$"), ".")
	comps := strings.Split(p, ".")
	cur := root
	for i, comp := range comps {
		if comp == "" {
			continue
		}
		last := i == len(comps)-1
		key, idx, hasIdx := comp, 0, false
		if o := strings.IndexByte(comp, '['); o >= 0 && strings.HasSuffix(comp, "]") {
			key = comp[:o]
			hasIdx = true
			fmt.Sscanf(comp[o+1:len(comp)-1], "%d", &idx)
		}
		if key != "" {
			m, ok := cur.(map[string]interface{})
			if !ok {
				return fmt.Errorf("not object")
			}
			if last && !hasIdx {
				m[key] = value
				return nil
			}
			v, ok := m[key]
			if !ok {
				return fmt.Errorf("missing")
			}
			cur = v
		}
		if hasIdx {
			a, ok := cur.([]interface{})
			if !ok || idx < 0 || idx >= len(a) {
				return fmt.Errorf("bad index")
			}
			if last {
				a[idx] = value
				return nil
			}
			cur = a[idx]
		}
	}
	return fmt.Errorf("unset")
}

// ─── param helpers ───────────────────────────────────────────────────────────

func wrap(err error) error { return fmt.Errorf("invalid params: %w", err) }

func strOpt(m map[string]interface{}, k string, dst *string) {
	if s, ok := m[k].(string); ok && s != "" {
		*dst = s
	}
}

func boolParam(m map[string]interface{}, k string, dst *bool) error {
	if v, ok := m[k]; ok {
		b, ok := v.(bool)
		if !ok {
			return fmt.Errorf("'%s' must be a boolean", k)
		}
		*dst = b
	}
	return nil
}

func toFloat(v interface{}) (float64, error) {
	switch n := v.(type) {
	case float64:
		return n, nil
	case float32:
		return float64(n), nil
	case int:
		return float64(n), nil
	case int64:
		return float64(n), nil
	case json.Number:
		return n.Float64()
	default:
		return 0, fmt.Errorf("not a number")
	}
}

func isASCIIPrintable(s string) bool {
	for _, r := range s {
		if r < 0x20 || r > 0x7E {
			return false
		}
	}
	return true
}
